In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.1+cu121


In [ ]:
#creating scalar tensor
scalar=torch.tensor(7)
scalar

tensor(7)

In [ ]:
#To check dimension of scalar
scalar.ndim

0

In [ ]:
#Get tensor back as Python int
scalar.item()

7

In [ ]:
#creating vector tensor
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim #checking dimension of vector

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#MATRIX
MATRIX=torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape


torch.Size([2, 2])

In [ ]:
#TENSOR
TENSOR=torch.tensor([[[1,2,3],[3,6,9],[2,4,5]
]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
###Random Tensors
# Why random tensors? Random tensors are important because the way many neural network is that they start with tensors full of random numbers and then
# adjust those random numbers to better represent the data
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.8600, 0.5942, 0.4555, 0.2170],
        [0.2143, 0.9415, 0.8018, 0.6294],
        [0.2179, 0.8468, 0.4923, 0.4504]])

In [ ]:
random_tensor.ndim

2

In [ ]:
random_tensor.shape

torch.Size([3, 4])

In [ ]:
#Create a random tensor with similar shape to an image tensor
random_image_size_tensor=torch.rand(size=(3,224,224)) #colour channel,heigh,width

In [ ]:
random_image_size_tensor

tensor([[[0.4139, 0.0702, 0.2789,  ..., 0.5052, 0.2282, 0.3250],
         [0.7571, 0.5102, 0.5760,  ..., 0.2371, 0.3976, 0.4231],
         [0.1397, 0.8048, 0.4411,  ..., 0.6818, 0.8437, 0.6523],
         ...,
         [0.2100, 0.8757, 0.5561,  ..., 0.7508, 0.0940, 0.1065],
         [0.0369, 0.3957, 0.6635,  ..., 0.6249, 0.1546, 0.4555],
         [0.3166, 0.6063, 0.6026,  ..., 0.1640, 0.7278, 0.1681]],

        [[0.0960, 0.4780, 0.5362,  ..., 0.3054, 0.1664, 0.3513],
         [0.6463, 0.5858, 0.2099,  ..., 0.0479, 0.7776, 0.8168],
         [0.0519, 0.1663, 0.7717,  ..., 0.7176, 0.3370, 0.8863],
         ...,
         [0.3757, 0.9006, 0.5979,  ..., 0.0770, 0.0840, 0.3844],
         [0.1902, 0.5491, 0.7854,  ..., 0.6342, 0.2208, 0.1729],
         [0.1517, 0.3869, 0.8951,  ..., 0.0252, 0.2383, 0.7598]],

        [[0.4017, 0.7458, 0.1171,  ..., 0.4190, 0.6983, 0.7226],
         [0.8945, 0.8590, 0.9196,  ..., 0.2355, 0.6992, 0.9426],
         [0.5280, 0.9871, 0.0541,  ..., 0.4764, 0.5485, 0.

In [ ]:
random_image_size_tensor.shape

torch.Size([3, 224, 224])

In [ ]:
random_image_size_tensor.ndim
#random_image_size_tensor.shape


3

In [ ]:
#create a tensor of all zeros
zeros=torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
#create a tensor of all ones
ones=torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
zeros.dtype

torch.float32

In [ ]:
one_to_ten=torch.arange(0,10)
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#Creating a range of tensors and tensors-like
#use torch.arange()
one_to_ten=torch.arange(start=0,end=10,step=2)
one_to_ten

tensor([0, 2, 4, 6, 8])

In [ ]:
#creating tensors like
ten_zeros=torch.zeros_like(input=one_to_ten) #if I want to take the shape of one_to_ten then we can use tensors like
ten_zeros

tensor([0, 0, 0, 0, 0])

Tensor Datatype
**Note**: Tensor Datatypes is one of the 3 big errors you will run into with Pytorch and deep Learning:


1.   Tensors not right datatype

2.   Tensors not right shape
3.   Tensors not on the right device

---








In [ ]:
float_32_tensor=torch.tensor([3.0,6.0,9.0],dtype=None,device=None,requires_grad=False)
float_32_tensor
#requires_grad means whether or not to track gradients with this tensors operations

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype


torch.float32

In [ ]:
#converting float32 in float16
float_16_tensor=float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor #sometimes in large neural network it shows  shape error


tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor=torch.tensor([3,6,9],dtype=torch.int64)
int_32_tensor

tensor([3, 6, 9])

In [ ]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

Getting information from tensors(attributes)


1.   Tensors not right datatype - to do get datatye from a tensor, can use 'tensor.dtype'
2.   Tensors not right shape- to get shape from a tensor,can use tensor.shape
3. Tensors not on the right device- to get device from a tensor can use tensor.device



In [ ]:
some_tensor=torch.rand(3,4)
some_tensor


tensor([[0.4256, 0.2179, 0.3951, 0.3037],
        [0.4555, 0.9629, 0.5032, 0.5779],
        [0.1883, 0.3235, 0.6053, 0.3131]])

In [ ]:
print(f"Datatype of tensor:{some_tensor.dtype}")
print(f"Shape of tensor:{some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

Datatype of tensor:torch.float32
Shape of tensor:torch.Size([3, 4])
Device tensor is on: cpu


Manipulating Tensors(tensor operations)

Tensor Operations include:


*   addition
*   subtraction


*   multiplication(element-wise)
*   division

*   matrix multiplication









In [ ]:
# Create a tensor add 10 to it
tensor=torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [ ]:
#multiply tensor by 10
tensor *10

tensor([10, 20, 30])

In [ ]:
tensor/10

tensor([0.1000, 0.2000, 0.3000])

In [ ]:
#substrate 10
tensor -10

tensor([-9, -8, -7])

Pytorch built-in-functions

In [ ]:
#Try out Pytorch buit-in-functions
torch.mul(tensor,10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor,10)

tensor([11, 12, 13])

Matrix Multiplication

Two main ways of matrix multiplication in neural networks and deep learning:


1.   Element-wise muliplication.
2.   Matrix multiplication.(dot product) (Inner dimension must match) (3,2) @ (3,2) won't work.Resulting matrix has the shape of outer dimensions.



In [ ]:
tensor * tensor #elementwise multiplication

tensor([1, 4, 9])

In [ ]:
#matrix multiplication
torch.matmul(tensor,tensor)

tensor(14)

See the time difference


In [ ]:
%%time
value =0
for i in range(len(tensor)):
  value+=tensor[i]*tensor[i]
print(value)

tensor(14)
CPU times: user 765 µs, sys: 0 ns, total: 765 µs
Wall time: 772 µs


In [ ]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 101 µs, sys: 7 µs, total: 108 µs
Wall time: 113 µs


tensor(14)

One of the most common errors in deep learning: Shape errors


In [ ]:
x=torch.matmul(torch.rand(3,2),torch.rand(2,9))
x


tensor([[0.1545, 0.1205, 0.2721, 0.2262, 0.0260, 0.3909, 0.2099, 0.0811, 0.4611],
        [0.2772, 0.5782, 0.9003, 0.4922, 0.0674, 0.8982, 0.6321, 0.3774, 1.0797],
        [0.0445, 0.4550, 0.5567, 0.1651, 0.0316, 0.3408, 0.3570, 0.2927, 0.4255]])

In [ ]:
x.shape

torch.Size([3, 9])

In [ ]:
tensor_A=torch.tensor([[1,2],[3,4],[5,6]])
tensor_B=torch.tensor([[7,10],[8,11],[9,12]])
torch.matmul(tensor_A,tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

To fix our tensor shape issues , we can manipulate the shape of one of our tensors using a transpose.

In [ ]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [ ]:
y=torch.matmul(tensor_A,tensor_B.T)
y

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [ ]:
y.shape

torch.Size([3, 3])

Finding min,max,sum,etc(tensor aggregation)

---



In [ ]:
x=torch.arange(0,100,10)
print(x)
x.dtype

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])


torch.int64

In [ ]:
#Find the min
torch.min(x),x.min()

(tensor(0), tensor(0))

In [ ]:
#Find the max
torch.max(x)

tensor(90)

In [ ]:
#Find the mean
torch.mean(x.type(torch.float32)) ##we need to see which datatype is coming and  and need to convert in float 32 for mean operation

tensor(45.)

In [ ]:
#Find the sum
torch.sum(x),x.sum()

(tensor(450), tensor(450))

Finding the positional min and max

In [ ]:
x=torch.arange(1,100,10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

For softmax activation argmin() and argmax() are basically applied

In [ ]:
#Find the position in tensor that has the minimum value with argmin()--> return index position
x.argmin()

tensor(0)

In [ ]:
x[0]

tensor(1)

In [ ]:
#Find the postion in tensor that has maximum value with argmax() --> return index position
x.argmax()

tensor(9)

Reshaping,stacking,squeezing and unsqueezing tensors




*   Reshaping - reshapes an input tensor to a defined shape
*  View-Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* stacking - combine multiple tensor on top of each other (vstack) or side by side
* Squeeze- removes all '1' dimension from a tensor
* Unsqueeze- add a '1' dimension to a target tensor
*Permute-Return a view of the input with dimension permuted(swapped) in a certain way



In [ ]:
import torch
x=torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
x_reshaped=x.reshape(1,9)
x_reshaped,x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

We need to maintain the shape for reshape case

In [ ]:
x_reshaped=x.reshape(9,1)
x_reshaped,x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [ ]:
#Change the view
z=x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
#Changing z changes x(because a view of a tensor shares the same memory as the original input)
z[:,0]=5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
#Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x],dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
x_stacked = torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_reshaped.shape

torch.Size([9, 1])

In [ ]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
x_reshaped.squeeze().shape

torch.Size([9])

In [ ]:
#torch.squeeze() - removes all single dimesions from a target tensor
print(f"Previous tensor:{x_reshaped}")
print(f"Previous shape:{x_reshaped.shape}")

#remove extra dimensions from x_reshaped
x_squeezed=x_reshaped.squeeze()
print(f"\nNew Tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor:tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
Previous shape:torch.Size([9, 1])

New Tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [ ]:
#torch.unsqueeze() - adds a single dimension to a target tensor at a specific dimensions

print(f"Previous target:{x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

#Add an etra dimensions with unsqueeze
x_unsqueezed=x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target:tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [ ]:
#torch.permute - rearranges the dimensions of a target tensor in a specified order

x_original = torch.rand(size=(224,224,3)) #[height,width,color_channels]

#Permute the original tensor to rearrange the axis(or dim) order

x_permuted=x_original.permute(2,0,1) #shift axis --> 0 to 1,1 to 2, 2 to 0

print(f"Previous shape: {x_original.shape}")
print(f"New shape : {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape : torch.Size([3, 224, 224])


In [ ]:
x_original[0,0,0] = 728218
x_original[0,0,0],x_permuted[0,0,0] #In both cases it is changing

(tensor(728218.), tensor(728218.))

Indexing(selecting data from tensors)

Indexing with Pytorch is similar to indexing with NumPy

In [ ]:
#Create a tensor
import torch
x=torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
#let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0][0] #Index on the middle bracket(dim=1)

tensor([1, 2, 3])

In [ ]:
x[0][2][2]

tensor(9)

In [ ]:
x[0][0][0] #Index on the most inner bracket(last dimension)

tensor(1)

In [ ]:
#You can also use ":" to select all of target dimensions
x[:,0]

tensor([[1, 2, 3]])

In [ ]:
#Get all values of 0th and 1st dimensions but only index1 of 2nd dimensions
x[:,:,1]

tensor([[2, 5, 8]])

In [ ]:
#Get all values of the 0 dimension but only the 1 index values of 2nd dimension
x[:,1,1]

tensor([5])

In [ ]:
#Get index of 0th and 1st dimensions and all values of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

In [ ]:
#Index on x to return 9
print(x[0][2][2])
#Index on x to return 3,6,9
print(x[:,:,2])

tensor(9)
tensor([[3, 6, 9]])


Pytorch Tensors and Numpy

Numpy is a popular scientific Python numerical computing library.

And because of this,Pytorch has functionality to interact with it.



*   Data in NumPy, want in Pytorch tensor-> torch.from_numpy(ndarray)
*   Pytorch tensor ->NumPy-> torch.Tensor.numpy()



In [ ]:
# NumPy array to Tensor
import torch
import numpy as np

array=np.arange(1.0,8.0)
tensor=torch.from_numpy(array) #warning when converting from numpy--> pytorch, pytorch reflects numpy's default datatype  of float64 unless specifed otherwise
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array.dtype

dtype('float64')

In [ ]:
# Change the value of array, what will this do to tensor? #Tensor will not change if array changes
array= array+1
array,tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
#Tensor to Numpy
tensor=torch.ones(7)
numpy_tensor=tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
#Change the tensor, what happens to numpy_tensor? #numpy_tensor remains same
tensor=tensor+1
tensor,numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

Reproducibility(trying to take random out of random)

In short how a neural network learns:
start with random numbers --> tensor operations --> update random numbers to try and make them better representations of data--> again --> again..


To reduce the randomness in neural networks and Pytorch comes the concept of **random seed**(pseudorandom random generator)

Essentially  what the random seed does is "flavour" the randomness.

In [ ]:
import torch

#create two random tensors
random_tensor_A=torch.rand(3,4)
random_tensor_B=torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A== random_tensor_B)

tensor([[0.7875, 0.2460, 0.0236, 0.3574],
        [0.1371, 0.8198, 0.9720, 0.4352],
        [0.8387, 0.1171, 0.8862, 0.5279]])
tensor([[0.0382, 0.9895, 0.4078, 0.0272],
        [0.8430, 0.9467, 0.2736, 0.9688],
        [0.8443, 0.6257, 0.3642, 0.5892]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
#Let's make some random but reproducible tensors
import torch
#set the random seed
RANDOM_SEED=42
torch.manual_seed(RANDOM_SEED)
random_tensor_C=torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D=torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C==random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Running tensors and Pytorch objects on GPUs (and making faster computations)


In [ ]:
!nvidia-smi

Tue Aug 13 06:36:49 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   55C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
#Chexk for GPU access with Pytorch
import torch
torch.cuda.is_available()

True

In [ ]:
#Select device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
#Count number of devices
torch.cuda.device_count()

1

Putting tensors(and models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations.

In [ ]:
#create a tensor
import torch
tensor=torch.tensor([1,2,3])
print(tensor,tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
#Move tensor to GPU(if available)
tensor_on_gpu=tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

Moving tensors back to the GPU

In [ ]:
#If tensors is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
#To fix the GPU tensor with Numpy issue, we can first set it to the CPU
tensor_back_on_cpu=tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [ ]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')